### ISSUE TITLE
Support customized Windows terminal profile.

### ISSUE THREAD

**Issue by Anduin2017** [lextm/windowsterminal-shell#1]
Hi, in my configuration file I have 4 profiles.

![image](https://user-images.githubusercontent.com/19531547/81131993-8ac4e700-8f7f-11ea-84e8-cec22ba843bf.png)

My settings:

```json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{11a66a21-0c86-4522-aa0d-415cce5f172c}",
    "profiles": {
        "defaults": {

        },
        "list": [
            {
                "guid": "{11a66a21-0c86-4522-aa0d-415cce5f172c}",
                "name": "Bash",
                "colorScheme": "Ubuntu",
                "fontFace": "Cascadia Code",
                "fontSize": 12,
                "commandline": "bash.exe",
                "icon": "ms-appx:///ProfileIcons/{574e775e-4f2a-5b96-ac1e-a2962a402336}.png",
                "hidden": false,
                "acrylicOpacity": 0.8,
                "useAcrylic": true
            },
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "cmd",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    "keybindings": [
        { "command": "paste", "keys": "ctrl+v" }
    ]
}
```

So how can I start the Windows terminal here with the default profile instead of selecting from CMD and PowerShell?

**Comment by Anduin2017** [comment]
I expect that the script could read the settings JSON file first and get all profiles in it, and add all found profiles to the context menu.

**Comment by lextm** [comment]
It would require an interactive PowerShell script, instead of the current hard coded `install.ps1`.

**Comment by lextm** [comment]
Some initial changes are made in 3839e917b2b5f1e862c3974f03c7ceb4e6016bc5

Please run `uninstall.ps1` and then `install.ps1` from master, and see if the result looks good enough.

**Comment by Anduin2017** [comment]
The script can be run successfully without error. But...

![image](https://user-images.githubusercontent.com/19531547/81186013-e5dcf500-8fe4-11ea-9401-797d7f215b51.png)

BTW, shall PowerShell 5 or PowerShell 7 be supported? Installing PowerShell 6 is very hard now.

**Comment by lextm** [comment]
Just noticed that your settings.json is using the "defaults"/"list" template. That requires different processing code, and should be fixed soon.

**Comment by lextm** [comment]
You might try the latest. I think I have resolved the issue completely.
