### ISSUE TITLE
Getting error while trying to install: The latest version found is less than 0.11, which is not tested. The install script might fail in certain way.

### ISSUE THREAD

**Issue by leniel** [lextm/windowsterminal-shell#12]
Hey, thanks for this add-on!

I tried installing it under WIndows Terminal Preview version. Is it supported?

```
Windows Terminal (Preview)
Version: 1.0.1402.0
```

By the way... I just installed WT Preview maybe 2 hours ago. Didn't restart the PC... maybe that's interfering.

![image](https://user-images.githubusercontent.com/764854/82492247-40358580-9abc-11ea-9470-81898e858e65.png)

**Comment by lextm** [comment]
This is an issue I am investigating.

Temp solution is to use the official 1.0 release.

**Comment by lextm** [comment]
Just added `--prerelease` switch. Please try out the latest commit.

If you run `install.ps1 --prerelease`, it picks up the preview version(s). When `install.ps1` runs, it skips the preview version(s).

Tested on one of my machines. Let me know if this works for you.

**Comment by lextm** [comment]
Just made some changes to `install.ps1` to follow PowerShell conventions, so now to work with Windows Terminal Preview the command line must be changed to `install.ps1 -prerelease`.
