### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by taooceros** [lextm/windowsterminal-shell#14]
```
ParserError: D:\Download\install.ps1:322
Line |
 322 |          <svg class="octicon octicon-sign-out v-align-middle" viewBox= …
     |                      ~~~~~~~
     | Unexpected token 'octicon' in expression or statement.
```

**Comment by lextm** [comment]
That's probably because you downloaded the wrong file.

You should either clone this repo to your local disk and run it, or download the raw file from https://raw.githubusercontent.com/lextm/windowsterminal-shell/master/install.ps1

**Comment by taooceros** [comment]
Oh, thanks!
