### ISSUE TITLE
Cannot open terminal via 'Windows Terminal Here as Administrator'

### ISSUE THREAD

**Issue by Markghz** [lextm/windowsterminal-shell#18]
After running the installation script I get the context menu. It works fine if I use  'Windows Terminal Here' for cmd, pwsh, etc. But when I want to open the terminal as administrator via 'Windows Terminal Here as Administrator', the powershell window and cmd window just flash on my screen and then nothing happens. 

I have check the registry for the running command as follows:

\HKEY_CLASSES_ROOT\Directory\ContextMenus\AddMenuTerminalAdmin\shell\{0caa0dad-35be-5f56-a8ff-afceeeaa6101}\command

PowerShell -WindowStyle Hidden -Command "Start-Process cmd.exe -WindowStyle Hidden -Verb RunAs -ArgumentList \"/c C:\Users\Kwan Hwaitzit\AppData\Local\Microsoft\WindowsApps\wt.exe -p \"\"命令提示符\"\" -d \"\"%V.\"\"\" "

Does it matter if there are spaces in my username? I tried to run the command directly with 'Windows Run' but got the same result.

**Comment by lextm** [comment]
Can you rerun the latest `install.ps1`? I fixed that yesterday.

Duplicate to #16

**Comment by Markghz** [comment]
I fixed that problem. Thank you!
