### ISSUE TITLE
error 0x80070002 on admin launch (Command Prompt)

### ISSUE THREAD

**Issue by AnthonyB28** [lextm/windowsterminal-shell#2]
When doing a shift + right click in a directory, going into 'Windows Terminal (Admin) here' -> Command Prompt or Windows Azure Shell, I get the following error:

> [error 0x80070002 when launching `Prompt -d C:\Users\abarranco\Downloads.']

> [error 0x80070002 when launching `Cloud Shell']

Powershell appears to function properly in admin though.
So does non-admin across all 3.

**Comment by lextm** [comment]
Thanks. Will fix it soon.

**Comment by lextm** [comment]
All except Azure Cloud Shell have been fixed, but the root cause for Azure Cloud Shell is miserable. So will leave this issue open for a while.
