### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by moritzmyrz** [lextm/windowsterminal-shell#20]
Hey, I am getting no icon when right-clicking. How can I fix this?
![image](https://user-images.githubusercontent.com/64229413/83307033-06732600-a204-11ea-8dd7-f44cf351def9.png)

**Comment by lextm** [comment]
Thanks for reporting this. I will take a look.

**Comment by lextm** [comment]
The issue was caused by Windows Terminal auto-update.

Currently some of the menu items link to the actual Windows Terminal executable to use its icon. That file path is version dependent, and becomes invalid during 0.11->1.0 upgrade.

The workaround is to rerun `install.ps1` which regenerates the menu items with the updated executable path.

**Comment by moritzmyrz** [comment]
Hello, the "main" one works now but for the cmd one, it's still blank. 
![image](https://user-images.githubusercontent.com/64229413/83353152-d1c0b500-a350-11ea-9d6d-1f4d21267cc1.png)

**Comment by noxifoxi** [comment]
Same here on mini:
![image](https://user-images.githubusercontent.com/293639/83353399-a6d76080-a352-11ea-85d6-f997b72dd420.png)

**Comment by lextm** [comment]
Fixed Windows Terminal icon cache issue in 828884c8e1e16535b5533d1aeb53ff008b665a6b

**Comment by lextm** [comment]
@noxifoxi Rerun the latest `install.ps1` with `Mini` switch should fix that.

**Comment by lextm** [comment]
@moritzmyrz Can you run `Get-ChildItem -Path Registry::HKEY_CLASSES_ROOT\Directory\ContextMenus\MenuTerminal\shell` at PowerShell console and let me know its output?

**Comment by moritzmyrz** [comment]
Yessir: https://hasteb.in/zucasufu.txt

**Comment by lextm** [comment]
@moritzmyrz Is `C:/Users/morit/Pictures/Saved Pictures/Icon1.ico` a valid icon file?

`install.ps1` takes that file path from your Windows Terminal settings.json file and writes it to Windows registry. So why Windows Explorer renders a blank icon is no longer related to the install script, but this icon alone.

**Comment by moritzmyrz** [comment]
Yeah, it is, I am using it for the tabs in the terminal so it works fine aside from the context menu.

**Comment by lextm** [comment]
@moritzmyrz Unfortunately Windows Explorer is not Windows Terminal. The latter is a modern app that supports a variety of image formats, while the former is known to only support ICO files (even with undocumented restrictions such as bitmap sizes and so on).

Like I explained above, the rendering problem is no longer an issue related to this install script, but the icon file alone, so I won't be able to help further.
