### ISSUE TITLE
Invalid JSON Primitive when installing

### ISSUE THREAD

**Issue by daves28** [lextm/windowsterminal-shell#21]
I run the script `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lextm/windowsterminal-shell/master/install.ps1'))`
And I get the following error: 
![image](https://user-images.githubusercontent.com/43623966/83338248-5ef00500-a290-11ea-8e08-8f3ccebdeab9.png)

The Windows Terminal option does then appear in the context menu but an error message pops up when clicking it saying there is no app associated with it.

**Comment by lextm** [comment]
Please share your settings.json file, `$env:LocalAppData\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`

**Comment by lextm** [comment]
The error happened because you were running PowerShell 5.1, not 7.0 as documented.

Just added an extra version check in 5b928f687c2dd49a88020024954f4674e1310923, as the requires statement does not work in one line execution approach.
