### ISSUE TITLE
Is it possible get shell information from setting file?

### ISSUE THREAD

**Issue by sewonist** [lextm/windowsterminal-shell#23]
Hi. I love your script. It's really useful about my shell life with windows. I never thought without it. Although, I need a little bit more feature. I really want to use with Anaconda shell also. I have several shells like below image.

![image](https://user-images.githubusercontent.com/352759/83460952-933b0f80-a4a2-11ea-8bb0-1a89f6b3a919.png)

And I want to run anaconda shell with context menu. I try to edit your code myself. Unfortunately, It's too difficult to me. So, I have an idea if is it possible making context to menu from Terminal setting. It's really good for me. 

Thanks again!!!

**Comment by lextm** [comment]
If you want extra shells, you should go and edit Windows Terminal settings first, and then rerun install.ps1.

I don’t think editing this script in the first place will help.

**Comment by sewonist** [comment]
WOW~~!!! It's already work with setting config file. I try to install again and it's work perfectly! Thanks!! 🍺

**Comment by lextm** [comment]
Aha, I see what you meant now.

Right. This install script is one time, so it won't be able to automatically update menu items when you update anything in Windows Terminal.

But rerun it and the new settings are picked up :)
