### ISSUE TITLE
Large PNGs aren't converted to icons 

### ISSUE THREAD

**Issue by mo523** [lextm/windowsterminal-shell#24]
I have a few shells that use custom pngs for their icons in terminal. When running the script they fail to convert to icons and throw errors instead. 

```
InvalidArgument:
Line |
 112 |          $iconWriter.Write([byte]$width);
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "285" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte."
```

(Happens on line 114 as well, same issue. Though why generate the icon twice)

I saw the script casts the width/height to a byte and my pngs were > 255. After resizing and rerunning the script it created them no problem. I guess it needs to resize them first or add a warning in the readme. 

Thanks for such a great script 👍

**Comment by lextm** [comment]
Thanks for reporting this. Yup, big images were not tested, so problems like this are expected. Will see how to revise the script to solve this.

**Comment by mo523** [comment]
Thanks. Took a crack at it myself and I seem to have figured it out, though it's the first time I everwrote powershell code. I'll submit a PR soon.
