### ISSUE TITLE
it removes every other application from the context menu

### ISSUE THREAD

**Issue by gauravniltech** [lextm/windowsterminal-shell#27]
it removed vscode and pycharm from the context menu. Now I am reinstalling them

**Comment by lextm** [comment]
More information is needed. Cannot reproduce this.

**Comment by gauravniltech** [comment]
add vscode to folder(not file) context menu just like the terminal(gives an option while installing). Then run the shell script, it will remove vscode from the context menu or any other non-windows applications like pycharm

**Comment by lextm** [comment]
The scripts only manipulate its own registry keys, like `HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\ContextMenus\MenuTerminal` which has no conflict with VSCode. I cannot comment on PyCharm as I don't use it.

You have to dig further if you want to know what happens.
