### ISSUE TITLE
i am getting this errors 

### ISSUE THREAD

**Issue by rakewave** [lextm/windowsterminal-shell#32]
![image](https://user-images.githubusercontent.com/30774866/89138806-12999d80-d53d-11ea-8c22-b4d497942448.PNG)
I have this version of Microsoft terminal
![version](https://user-images.githubusercontent.com/30774866/89138873-483e8680-d53d-11ea-815b-4c01d83ceabe.PNG)

**Comment by lextm** [comment]
On a 64 bit Windows machine, you shouldn't launch PowerShell x86.
