### ISSUE TITLE
Error trying to install with Windows Terminal Preview v1.2

### ISSUE THREAD

**Issue by gabrielizalo** [lextm/windowsterminal-shell#33]
I'm getting this error:

![Error](https://user-images.githubusercontent.com/656353/89320618-4f51bb80-d647-11ea-984d-4fd6914f5c59.png)

**Comment by Gliptal** [comment]
Same error.

**Comment by srezasm** [comment]
Yes. these versions of scripts are not working for preview versions.
install path of windows terminal preview is `C:\Users\sreza\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe` however the used path in install.ps1 is `C:\Users\sreza\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe`.
I have not enough experience to change this scripts but it might be easy to update to the new version 😉

**Comment by lextm** [comment]
Duplicate to #12. But I just updated the script so it now shows a better error message to guide you.

**Comment by gabrielizalo** [comment]
It worked.. Thanksss  👍

**Comment by srezasm** [comment]
> It worked. Thanksss 👍

now it's working on preview version too?

**Comment by gabrielizalo** [comment]
> > It worked. Thanksss 👍
> 
> now it's working on preview version too?

Yes. Download the latest repo version and runs `.\install.ps1 -prerelease`.

![EVp51NQ9Gy](https://user-images.githubusercontent.com/656353/90135511-5f008c80-dd38-11ea-9b37-a95826424d9d.png)
