### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alannt777** [lextm/windowsterminal-shell#36]
```
Get-ChildItem:
Line |
 163 |      $versionFolders = (Get-ChildItem $root | Where-Object {
     |                         ~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Program Files (x86)\WindowsApps' because it does not exist.
GetProgramFilesFolder:
Line |
 389 |      $folder = GetProgramFilesFolder $includePreview
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to find Windows Terminal actual folder under C:\Program Files (x86)\WindowsApps. To install menu items for Windows Terminal Preview, run with "-Prerelease" switch Exit.
```

**EDIT:** Using PowerShell Core 7.0.3 and Windows Terminal Preview 1.4.2652.0

**Comment by lextm** [comment]
Can you run `Get-Command pwsh.exe` at PowerShell prompt and show its output?

**Comment by alannt777** [comment]
Here's the output:
```

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pwsh.exe                                           7.0.3.0    C:\Program Files (x86)\PowerSh…
```

**Comment by lextm** [comment]
You are using x86 build of PowerShell 7 on x64 build of Windows 10. That's not supported by the scripts.

Please install x64 build of PowerShell 7 and try again.

**Comment by alannt777** [comment]
@lextm That fixed the first error. But the second error (`Failed to find Windows Terminal actual folder...`) is still there. Your README.md (and also the error message) is a bit unclear on the instructions for WT Preview.

I tried this:
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lextm/windowsterminal-shell/master/install.ps1')) -Prerelease
``` 

But it said:
```
Invoke-Expression: A parameter cannot be found that matches parameter name 'Prerelease'.
```

**Comment by alannt777** [comment]
What am I doing wrong?

**Comment by lextm** [comment]
The PowerShell cmdlet `iex` does not allow you to pass any switch. You have to use workarounds like https://stackoverflow.com/questions/33206285/how-to-pass-arguments-to-an-invoke-expression-in-powershell

**Comment by alannt777** [comment]
I think you should make that clear in README.md

**Comment by lextm** [comment]
That's a PowerShell limitation, not something wrong with this project.
