### ISSUE TITLE
Seeking mouse might not be efficiency enough for users only prefer one shell.

### ISSUE THREAD

**Issue by Anduin2017** [lextm/windowsterminal-shell#4]
![image](https://user-images.githubusercontent.com/19531547/81262804-15d1da00-9071-11ea-96f7-d04c0295bf22.png)

Some users may only use one terminal. For me, I only use bash and never touch cmd or PowerShell.

But to open a terminal here, I have to seek my mouse. That is hard on a high-resolution screen.

Users types:
* A: Only prefer one shell. Requires the best efficiency.
* B: May switch shells. Requires a sub-menu.

I suggest there could be an option to switch. If the user prefers one default shell, there won't gonna create any submenu but only two options:

* Open Windows Terminal here
* Open Windows Terminal here(Admin)

And always open terminal with the default profile.

![image](https://user-images.githubusercontent.com/19531547/81263090-a01a3e00-9071-11ea-88ee-a395c53b457e.png)

**Comment by lextm** [comment]
Added a flat layout.

I think there can be another "mini" layout to only launch Windows Terminal (with default profile(s)) like you described. Should be ready soon.

**Comment by lextm** [comment]
You can try out the mini layout by running `install.ps1 mini`. To uninstall, run `uninstall.ps1 mini`.
