### ISSUE TITLE
(CLOSED) Missing icons when running as not admin

### ISSUE THREAD

**Issue by rgsura** [lextm/windowsterminal-shell#40]
Title self-explanatory. Talking about default layout. In administrator mode, all icons are correct, but in non-admin more, they are all blank

**Comment by lextm** [comment]
What do you mean by "in non-admin more, they are all blank"? Did you try to run `install.ps1` as non-admin?

**Comment by rgsura** [comment]
It actually got fixed by itself. Maybe because I put it to sleep or something

![Screenshot (77)](https://user-images.githubusercontent.com/52320472/96889928-64d8c380-1487-11eb-9948-8b1067d51f0c.png)
These icons when you hover over _Windows Terminal here_, were blank, but the icons when you hover over the _Windows Terminal here as administrator_, the icons were appearing correctly. Now they both work.

Keep up the good work, wanted a lot such a feature, like a lot what you made
