### ISSUE TITLE
Elevated Process' fails as VBS does not have a ScriptEngine

### ISSUE THREAD

**Issue by Hejle** [lextm/windowsterminal-shell#42]
When trying to start any of the Elevated Terminals using the vbs script I get an error saying: 

"There is no script engine for file extension .vbs"...

I am not sure why I can't run the .vbs file - I have even followed the SO post here
https://stackoverflow.com/questions/17757248/error-there-is-no-script-engine-for-file-extension-vbs-when-using-git-bash

I also get the error if I try to execute the vbs file manually (Or any vbs file)

Is it possible to create the Elevated Command without using vbs-files?

**Comment by lextm** [comment]
Fixing VBScript related issues on your machine is out of scope. No plan to modify the scripts of this project either.
