### ISSUE TITLE
Doesn't work with Powershell 7.1 Store Version

### ISSUE THREAD

**Issue by validatedev** [lextm/windowsterminal-shell#43]
It says it is installed, but it seems that it's not.

**Comment by lextm** [comment]
Duplicate of #37 

I don't know why Microsoft shipped PowerShell via the store, but you shouldn't use it at all as it comes with tons of limitation.

**Comment by BobenHome** [comment]
so what is final answer?

**Comment by lextm** [comment]
By design. The Store version of PowerShell is not supported.
