### ISSUE TITLE
With the latest version of terminal (Windows Terminal Preview v1.5.3242.0), the script "deafult" not working correctly

### ISSUE THREAD

**Issue by SiriosDev** [lextm/windowsterminal-shell#45]
![Cattura](https://user-images.githubusercontent.com/26876994/100525570-2c34b400-31c2-11eb-891d-85c2f6a45321.JPG)
(The Instance does not start).
The script working instead with Minimal e Flat

**Comment by lextm** [comment]
Cannot reproduce the issue. Can you try to run uninstall.ps1 first and then run install.ps1 again?

**Comment by SiriosDev** [comment]
![Cattura](https://user-images.githubusercontent.com/26876994/100550130-0d90f480-3278-11eb-9572-81c766bd0cdb.JPG)

**Comment by lextm** [comment]
Your only option now is to use PowerShell ISE or VSCode with PowerShell extension to debug `install.ps1` with break points. That can reveal what exactly happens on your machine and what might be wrong.

**Comment by SiriosDev** [comment]
Solved! I didn't know that a custom terminal had to have a guid😅. 

There is only one last little problem, I've set a custom icon for wsl bash but the administrator context menu (the normal work correctly) shows the Linux penguin instead of my custom icon.
![Cattura](https://user-images.githubusercontent.com/26876994/100555620-e4368f80-329c-11eb-9d6e-d513b4ffc057.JPG)
These ☝ are the rows in settings.json

**Comment by SiriosDev** [comment]
Solved! I didn't know that a custom terminal had to have a guid😅.

**Comment by jjavierdguezas** [comment]
It seems that if you create a new profile via Windows Terminal UI, it won't give it a guid, so you'll need to edit the `settings.json` manually
