### ISSUE TITLE
Wrong Order Of profiles

### ISSUE THREAD

**Issue by PitchAbyss** [lextm/windowsterminal-shell#57]
hi everyone i have setup few profiles which appears ok inside the terminal 

![image](https://github.com/lextm/windowsterminal-shell/assets/13099434/2bba0a61-9ac5-4ecb-abe5-2004a5c20d91)

but when i run the script all appears to be misorder please can someone help

![image](https://github.com/lextm/windowsterminal-shell/assets/13099434/3f92d89f-16fa-411f-ada3-030ca195d4e0)

**Comment by PitchAbyss** [comment]
@lextm sir any temp way to fix it ?

**Comment by slurdge** [comment]
I have a fix if you are open to PR @lextm

**Comment by slurdge** [comment]
Here you go:
https://github.com/lextm/windowsterminal-shell/pull/58

**Comment by PitchAbyss** [comment]
> Here you go: #58

thankyou sir let me find how to get this now

**Comment by PitchAbyss** [comment]
> Here you go: #58

thankyou so much sir this worked like a charm 🗡️
