### ISSUE TITLE
Windows terminal here->Ubuntu 20.04 command doesn't work properly

### ISSUE THREAD

**Issue by madfisht3** [lextm/windowsterminal-shell#9]
Hello.
I tried to run Windows terminal here->Ubuntu 20.04 command but it didn't work properly.
It set ~ directory instead of the selected directory path.

**Comment by lextm** [comment]
Can you share your Windows Terminal settings file?

**Comment by lextm** [comment]
Seem to be related to WSL. Will investigate.

**Comment by lextm** [comment]
You might rerun the latest version of `install.ps1` to resolve the issue. Now the script can understand dynamic profiles better to locate the right icon.

**Comment by madfisht3** [comment]
It works properly. Well done.
